version: '3'

tasks:
  test:
    desc: Run all internal tests
    cmds:
      - go test ./... -v

  build:
    desc: Build service
    cmds:
      - go build -o build/que cmd/que/main.go {{.CLI_ARGS}}

  docker-build:
    desc: Build service with docker
    cmds:
      - docker build . {{.CLI_ARGS}}

  gen-all:
    desc: Run all go:generate in project
    cmds:
      - go generate ./...

  run:
    desc: Run service
    cmds:
      - go run cmd/que/main.go {{.CLI_ARGS}}

  help:
    desc: Get configuration options help
    cmds:
      - go run cmd/que/main.go -help

  set-example:
    desc: Set example configuration and environment for test
    cmds:
      - cmd: xcopy configs/config.example.yml configs/config.yml /Y
        platforms: [windows]
      - cmd: cp -f configs/config.example.yml configs/config.yml
  
