logger:
  targets: [] # default # Targets(addresses) to which the logger sends logs
  dir: logs # default # Directory to store logs
  debug: false # default # Debug mode

bot:
  token: <your-telegram-bot-api-token> # required # Token is bot father telegram token for bot api
  long_poller_timeout: 10 # default # LongPollerTimeout is time(in seconds) of response waiting

queue_dispatcher:
  cache_size: 1024 # default # CacheSize is how many queue can be stored in cache
  cache_ttl: 86400 # default # CacheTTL is how long(in seconds) queue can be stored in cache