name: Publish Docker Image to GHCR

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Git tag
        id: get-tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/v}"
          echo "trimmed_tag=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "Original tag: ${GITHUB_REF#refs/tags/}"
          echo "Trimmed tag: ${TAG_NAME}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.get-tag.outputs.tag_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}